_target_: src.models.ddpm_cfg_module.DDPM_CFG_Module
cfg_scale: 3
label_drop_rate: 0.1
num_classes: 10
img_size: 32
noise_steps: 1000
in_channels: 3

diffusion: 
  _target_: src.models.components.diffusion.Diffusion
  noise_steps: 1000
  beta_start: 1e-4
  beta_end: 0.02
  img_size: 32
  num_classes: 10
  in_channels: 3
  out_channels: 3
  noise_schedule: linear


optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10


net:
  _target_: src.models.components.ddpm_cfg_unet_2d.ConditionedUnet
  in_channels: 3
  out_channels: 3
  block_count: 3
  num_classes: 10
  init_depth: 64
  depth_multiplier: 2
  time_dim: 256
  remove_deep_conv: False


