_target_: src.models.classification_module.ClassificationModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.simple_cnn_net.SimpleCNN
  hidden_dim_list: [3, 64, 128, 128, 256]
  output_size: 10