_target_: src.models.classification_module.ClassificationModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.vit.ViT
  input_channel: 3
  img_size: 32
  patch_size: 8
  dim: 128
  num_of_heads: 8
  dropout: 0.1
  expansion: 4
  depth: 12
  output_size: 10